language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jimmy2952/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jimmy2952/docker-react npm run test